#Chapter 1
image 1chapter1 = "images/scenes/chapter1/1chapter1.webp"
image 2chapter1 = "images/scenes/chapter1/2chapter1.webp"
image 3chapter1 = "images/scenes/chapter1/3chapter1.webp"
image 4chapter1 = "images/scenes/chapter1/4chapter1.webp"
image 6chapter1 = "images/scenes/chapter1/6chapter1.webp"

#image kimintro

image 8chapter1 = "images/scenes/chapter1/8chapter1.webp"
image 9chapter1 = "images/scenes/chapter1/9chapter1.webp"
image 10chapter1 = "images/scenes/chapter1/10chapter1.webp"
image 11chapter1 = "images/scenes/chapter1/11chapter1.webp"
image 12chapter1 = "images/scenes/chapter1/12chapter1.webp"
image 13chapter1 = "images/scenes/chapter1/13chapter1.webp"
image 14chapter1 = "images/scenes/chapter1/14chapter1.webp"
image 15chapter1 = "images/scenes/chapter1/15chapter1.webp"
image 16chapter1 = "images/scenes/chapter1/16chapter1.webp"
image 17chapter1 = "images/scenes/chapter1/17chapter1.webp"
image 18chapter1 = "images/scenes/chapter1/18chapter1.webp"
image 19chapter1 = "images/scenes/chapter1/19chapter1.webp"
image 20chapter1 = "images/scenes/chapter1/20chapter1.webp"
image 21chapter1 = "images/scenes/chapter1/21chapter1.webp"
image 22chapter1 = "images/scenes/chapter1/22chapter1.webp"
image 23chapter1 = "images/scenes/chapter1/23chapter1.webp"
image 24chapter1 = "images/scenes/chapter1/24chapter1.webp"
image 25chapter1 = "images/scenes/chapter1/25chapter1.webp"
image 26chapter1 = "images/scenes/chapter1/26chapter1.webp"

image chapter1reactions:
    "images/scenes/chapter1/chapter1reactionsA.webp"
    pause .05
    "images/scenes/chapter1/chapter1reactionsB.webp"
    pause .05
    "images/scenes/chapter1/chapter1reactionsC.webp"

image computerwithrecords = "images/scenes/chapter1/computerwithgraphs.webp"

#chapter2
image 1chapter2 = "images/scenes/chapter2/1chapter2.webp"
image 2chapter2 = "images/scenes/chapter2/2chapter2.webp"
image 3chapter2 = "images/scenes/chapter2/3chapter2.webp"
image 4chapter2 = "images/scenes/chapter2/4chapter2.webp"
image 5chapter2 = "images/scenes/chapter2/5chapter2.webp"
image 6chapter2 = "images/scenes/chapter2/6chapter2.webp"
image 7chapter2 = "images/scenes/chapter2/7chapter2.webp"
image 8chapter2 = "images/scenes/chapter2/8chapter2.webp"
image 9chapter2 = "images/scenes/chapter2/9chapter2.webp"
image 10chapter2 = "images/scenes/chapter2/10chapter2.webp"
image 11chapter2 = "images/scenes/chapter2/11chapter2.webp"
image 12chapter2 = "images/scenes/chapter2/12chapter2.webp"
image 13chapter2 = "images/scenes/chapter2/13chapter2.webp"
image 14chapter2 = "images/scenes/chapter2/14chapter2.png"
image 15chapter2 = "images/scenes/chapter2/15chapter2.png"

image messyfloor= "images/scenes/chapter2/messyfloor.webp"
image deskwithbook = "images/scenes/chapter2/deskwithbook.webp"
image nightfloor1 = "images/scenes/chapter2/nightfloor1.webp"
image nightfloor2 = "images/scenes/chapter2/nightfloor2.webp"
image nightfloor3 = "images/scenes/chapter2/nightfloor3.webp"

image lisafootball:
    "xxx/LisaFootball/lisagaze_00.png"
    pause .05
    "xxx/LisaFootball/lisagaze_01.png"
    pause .05
    "xxx/LisaFootball/lisagaze_02.png"
    pause .05
    "xxx/LisaFootball/lisagaze_03.png"
    pause .05
    "xxx/LisaFootball/lisagaze_04.png"
    pause .05
    "xxx/LisaFootball/lisagaze_05.png"
    pause .05
    "xxx/LisaFootball/lisagaze_06.png"
    pause .05
    "xxx/LisaFootball/lisagaze_07.png"
    pause .05
    "xxx/LisaFootball/lisagaze_08.png"
    pause .05
    "xxx/LisaFootball/lisagaze_09.png"
    pause .05
    "xxx/LisaFootball/lisagaze_10.png"
    pause .05
    "xxx/LisaFootball/lisagaze_11.png"
    pause .05
    "xxx/LisaFootball/lisagaze_12.png"
    pause .05
    "xxx/LisaFootball/lisagaze_13.png"
    pause .05
    "xxx/LisaFootball/lisagaze_14.png"


#chapter3
image 1chapter3 = "images/scenes/chapter3/1chapter3.webp"
image 2chapter3 = "images/scenes/chapter3/2chapter3.webp"
image 3chapter3 = "images/scenes/chapter3/3chapter3.webp"
image 4chapter3 = "images/scenes/chapter3/4chapter3.webp"
image 5chapter3 = "images/scenes/chapter3/5chapter3.webp"
image 6chapter3 = "images/scenes/chapter3/6chapter3.webp"
image 7chapter3 = "images/scenes/chapter3/7chapter3.webp"
image 8chapter3 = "images/scenes/chapter3/8chapter3.webp"
image 9chapter3 = "images/scenes/chapter3/9chapter3.webp"
image 10chapter3 = "images/scenes/chapter3/10chapter3.webp"
image 11chapter3 = "images/scenes/chapter3/11chapter3.webp"
image 12chapter3 = "images/scenes/chapter3/12chapter3.webp"
image 13chapter3 = "images/scenes/chapter3/13chapter3.webp"
image 14chapter3 = "images/scenes/chapter3/14chapter3.webp"
image 15chapter3 = "images/scenes/chapter3/15chapter3.webp"
image 16chapter3 = "images/scenes/chapter3/16chapter3.webp"
image 17chapter3 = "images/scenes/chapter3/17chapter3.webp"
image 18chapter3 = "images/scenes/chapter3/18chapter3.webp"
image 19chapter3 = "images/scenes/chapter3/19chapter3.webp"
image 20chapter3 = "images/scenes/chapter3/20chapter3.webp"
image 21chapter3 = "images/scenes/chapter3/21chapter3.webp"
image 22chapter3 = "images/scenes/chapter3/22chapter3.webp"
image 23chapter3 = "images/scenes/chapter3/23chapter3.webp"
image 24chapter3 = "images/scenes/chapter3/24chapter3.webp"
image 25chapter3 = "images/scenes/chapter3/25chapter3.webp"
image 26chapter3 = "images/scenes/chapter3/26chapter3.webp"
image 27chapter3 = "images/scenes/chapter3/27chapter3.webp"
image 28chapter3 = "images/scenes/chapter3/28chapter3.webp"
image 29chapter3 = "images/scenes/chapter3/29chapter3.webp"
image 30chapter3 = "images/scenes/chapter3/30chapter3.webp"
image 31chapter3 = "images/scenes/chapter3/31chapter3.webp"
image 32chapter3 = "images/scenes/chapter3/32chapter3.webp"
image 33chapter3 = "images/scenes/chapter3/33chapter3.webp"
image 34chapter3 = "images/scenes/chapter3/34chapter3.webp"
image 35chapter3 = "images/scenes/chapter3/35chapter3.webp"

image bellatape1 = "images/scenes/chapter3/bellatape1.webp"
image bellatape2 = "images/scenes/chapter3/bellatape2.webp"
image bellatape3 = "images/scenes/chapter3/bellatape3.webp"
image bellatape4 = "images/scenes/chapter3/bellatape4.webp"
image bellatape5 = "images/scenes/chapter3/bellatape5.webp"

image kimtape1 = "images/scenes/chapter3/kimtape1.webp"
image kimtape2 = "images/scenes/chapter3/kimtape2.webp"
image kimtape3 = "images/scenes/chapter3/kimtape3.webp"
image kimtape4 = "images/scenes/chapter3/kimtape4.webp"
image kimtape5 = "images/scenes/chapter3/kimtape5.webp"
image kimtape6 = "images/scenes/chapter3/kimtape6.webp"

image lisatape1 = "images/scenes/chapter3/lisatape1.webp"
image lisatape2 = "images/scenes/chapter3/lisatape2.webp"
image lisatape3 = "images/scenes/chapter3/lisatape3.webp"
image lisatape4 = "images/scenes/chapter3/lisatape4.webp"
image lisatape5 = "images/scenes/chapter3/lisatape5.webp"

image maitape1 = "images/scenes/chapter3/maitape1.webp"
image maitape2 = "images/scenes/chapter3/maitape2.webp"
image maitape3 = "images/scenes/chapter3/maitape3.webp"
image maitape4 = "images/scenes/chapter3/maitape4.webp"
image maitape5 = "images/scenes/chapter3/maitape5.webp"
image maitape6 = "images/scenes/chapter3/maitape6.webp"
image maitape7 = "images/scenes/chapter3/maitape7.webp"

#Chapter4
#Kim
image 1kimtalk = "images/scenes/chapter4/1kimtalk.webp"
image 2kimtalk = "images/scenes/chapter4/2kimtalk.webp"
image 3kimtalk = "images/scenes/chapter4/3kimtalk.webp"
image 4kimtalk = "images/scenes/chapter4/4kimtalk.webp"
image 5kimtalk = "images/scenes/chapter4/5kimtalk.webp"
image 6kimtalk = "images/scenes/chapter4/6kimtalk.webp"
image 7kimtalk = "images/scenes/chapter4/7kimtalk.webp"

#Lisa
image 1lisaprivate1 = "images/scenes/chapter4/1lisaprivate1.webp"
image 2lisaprivate1 = "images/scenes/chapter4/2lisaprivate1.webp"
image 3lisaprivate1 = "images/scenes/chapter4/3lisaprivate1.webp"
image 4lisaprivate1 = "images/scenes/chapter4/4lisaprivate1.webp"
image 5lisaprivate1 = "images/scenes/chapter4/5lisaprivate1.webp"
image 6lisaprivate1 = "images/scenes/chapter4/6lisaprivate1.webp"
image 7lisaprivate1 = "images/scenes/chapter4/7lisaprivate1.webp"
image 8lisaprivate1 = "images/scenes/chapter4/8lisaprivate1.webp"
image 9lisaprivate1 = "images/scenes/chapter4/9lisaprivate1.webp"
image 10lisaprivate1 = "images/scenes/chapter4/10lisaprivate1.webp"
image 11lisaprivate1 = "images/scenes/chapter4/11lisaprivate1.webp"
image 12lisaprivate1 = "images/scenes/chapter4/12lisaprivate1.webp"
image 13lisaprivate1 = "images/scenes/chapter4/13lisaprivate1.webp"
image 14lisaprivate1 = "images/scenes/chapter4/14lisaprivate1.webp"
image 15lisaprivate1 = "images/scenes/chapter4/15lisaprivate1.webp"
image 16lisaprivate1 = "images/scenes/chapter4/16lisaprivate1.webp"
image 17lisaprivate1 = "images/scenes/chapter4/17lisaprivate1.webp"
image 18lisaprivate1 = "images/scenes/chapter4/18lisaprivate1.webp"

image 23lisaprivate1 = "images/scenes/chapter4/23lisaprivate1.webp"

image 26lisaprivate1 = "images/scenes/chapter4/26lisaprivate1.webp"
image 27lisaprivate1 = "images/scenes/chapter4/27lisaprivate1.webp"
image 28lisaprivate1 = "images/scenes/chapter4/28lisaprivate1.webp"
image 29lisaprivate1 = "images/scenes/chapter4/29lisaprivate1.webp"
image 30lisaprivate1 = "images/scenes/chapter4/30lisaprivate1.webp"
image 31lisaprivate1 = "images/scenes/chapter4/31lisaprivate1.webp"
image 32lisaprivate1 = "images/scenes/chapter4/32lisaprivate1.webp"
image 33lisaprivate1 = "images/scenes/chapter4/33lisaprivate1.webp"
image 34lisaprivate1 = "images/scenes/chapter4/34lisaprivate1.webp"
image 35lisaprivate1 = "images/scenes/chapter4/35lisaprivate1.webp"

image lisashower1 = "xxx/Lisa/lisashower1.webp"
image lisashower2 = "xxx/Lisa/lisashower2.webp"
image lisashower3 = "xxx/Lisa/Lisashower3.webp"
image lisainbed = "images/scenes/chapter4/lisa bed 2.webp"
image lisanote = "images/scenes/chapter4/Lisasnote.webp"

image lisagym1 = "images/scenes/chapter4/lisagym1.webp"
image lisagym2 = "images/scenes/chapter4/lisagym2.webp"
image lisagym3 = "images/scenes/chapter4/lisagym3.webp"
image lisagym4 = "images/scenes/chapter4/lisagym4.webp"
image lisagym5 = "images/scenes/chapter4/lisagym5.webp"
image lisagym6 = "images/scenes/chapter4/lisagym6.webp"
image lisagym7 = "images/scenes/chapter4/lisagym7.webp"
image lisagym8 = "images/scenes/chapter4/lisagym8.webp"
image lisagym9 = "images/scenes/chapter4/lisagym9.webp"
image lisagym10 = "images/scenes/chapter4/lisagym10.webp"
image lisagym11 = "images/scenes/chapter4/lisagym11.webp"
image lisagym12 = "images/scenes/chapter4/lisagym12.webp"
image lisagym13 = "images/scenes/chapter4/lisagym13.webp"
image lisagym14 = "images/scenes/chapter4/lisagym14.webp"
image lisagym15 = "images/scenes/chapter4/lisagym15.webp"
image lisagym16 = "images/scenes/chapter4/lisagym16.webp"
image lisagym17 = "images/scenes/chapter4/lisagym17.webp"
image lisagym18 = "images/scenes/chapter4/lisagym18.webp"
image lisagym19 = "images/scenes/chapter4/lisagym19.webp"
image lisagym20 = "images/scenes/chapter4/lisagym20.webp"
image lisagym21 = "images/scenes/chapter4/lisagym21.webp"
image lisagym22 = "images/scenes/chapter4/lisagym22.webp"
image lisagym23 = "images/scenes/chapter4/lisagym23.webp"
image lisagym24 = "images/scenes/chapter4/lisagym24.webp"
image lisagym25 = "images/scenes/chapter4/lisagym25.webp"
image lisagym26 = "images/scenes/chapter4/lisagym26.webp"

#Mai
image 1maiprivate1 = "images/scenes/chapter4/1maiprivate1.webp"
image 2maiprivate1 = "images/scenes/chapter4/2maiprivate1.webp"
image 3maiprivate1 = "images/scenes/chapter4/3maiprivate1.webp"
image 4maiprivate1 = "images/scenes/chapter4/4maiprivate1.webp"
image 5maiprivate1 = "images/scenes/chapter4/5maiprivate1.webp"
image 6maiprivate1 = "images/scenes/chapter4/6maiprivate1.webp"
image 7maiprivate1 = "images/scenes/chapter4/7maiprivate1.webp"
image 8maiprivate1 = "images/scenes/chapter4/8maiprivate1.webp"
image 9maiprivate1 = "images/scenes/chapter4/9maiprivate1.webp"
image 10maiprivate1 = "images/scenes/chapter4/10maiprivate1.webp"
image 11maiprivate1 = "images/scenes/chapter4/11maiprivate1.webp"
image 12maiprivate1 = "images/scenes/chapter4/12maiprivate1.webp"
image 13maiprivate1 = "images/scenes/chapter4/13maiprivate1.webp"
image 14maiprivate1 = "images/scenes/chapter4/14maiprivate1.webp"
image 15maiprivate1 = "images/scenes/chapter4/15maiprivate1.webp"
image 16maiprivate1 = "images/scenes/chapter4/16maiprivate1.webp"
image 17maiprivate1 = "images/scenes/chapter4/17maiprivate1.webp"
image 18maiprivate1 = "images/scenes/chapter4/18maiprivate1.webp"
image 19maiprivate1 = "images/scenes/chapter4/19maiprivate1.webp"
image 20maiprivate1 = "images/scenes/chapter4/20maiprivate1.webp"

#Crissy
image crissyinspect1 = "images/scenes/chapter4/crissyinspect1.webp"
image crissyinspect2 = "images/scenes/chapter4/crissyinspect2.webp"
image crissyinspect3 = "images/scenes/chapter4/crissyinspect3.webp"
image crissyinspect4 = "images/scenes/chapter4/crissyinspect4.webp"
image crissyinspect5 = "images/scenes/chapter4/crissyinspect5.webp"
image crissyinspect6 = "images/scenes/chapter4/crissyinspect6.webp"
#--------------
#Chapter5
#MC/Office/Home
image mchomealone1 = "images/scenes/chapter5/mchomealone1.webp"
image mchomealone2 = "images/scenes/chapter5/mchomealone2.webp"
image mchomealone3 = "images/scenes/chapter5/mchomealone3.webp"
image mchomealone4 = "images/scenes/chapter5/mchomealone4.webp"

image messyoffice = "images/scenes/chapter5/messy office1.webp"
image messyoffice2 = "images/scenes/chapter5/messy office2.webp"

image outsideofficewithpolice = "images/scenes/chapter5/outsideofficewith police.webp"

image investigatoratoffice1 = "images/scenes/chapter5/investigatoratoffice1.webp"
image investigatoratoffice2 = "images/scenes/chapter5/investigatoratoffice2.webp"
image investigatoratoffice3 = "images/scenes/chapter5/investigatoratoffice3.webp"
image investigatoratoffice4 = "images/scenes/chapter5/investigatoratoffice4.webp"

image 1chapter5 = "images/scenes/chapter5/1chapter5.webp"
image 2chapter5 = "images/scenes/chapter5/2chapter5.webp"
image 3chapter5 = "images/scenes/chapter5/3chapter5.webp"
image 4chapter5 = "images/scenes/chapter5/4chapter5.webp"
image 5chapter5 = "images/scenes/chapter5/5chapter5.webp"
image 6chapter5 = "images/scenes/chapter5/6chapter5.webp"

image kimprank1 = "images/scenes/chapter5/kimprank1.webp"
image kimprank2 = "images/scenes/chapter5/kimprank2.webp"
image kimprank3 = "images/scenes/chapter5/kimprank3.webp"
image kimprank4 = "images/scenes/chapter5/kimprank4.webp"

image lisamaitalk1 = "images/scenes/chapter5/lisamaitalk1.webp"
image lisamaitalk2 = "images/scenes/chapter5/lisamaitalk2.webp"
image lisamaitalk3 = "images/scenes/chapter5/lisamaitalk3.webp"
image lisamaitalk4 = "images/scenes/chapter5/lisamaitalk4.webp"
image lisamaitalk5 = "images/scenes/chapter5/lisamaitalk5.webp"
image lisamaitalk6 = "images/scenes/chapter5/lisamaitalk6.webp"
image lisamaitalk7 = "images/scenes/chapter5/lisamaitalk7.webp"
image lisamaitalk8 = "images/scenes/chapter5/lisamaitalk8.webp"
image lisamaitalk9 = "images/scenes/chapter5/lisamaitalk9.webp"
image lisamaitalk10 = "images/scenes/chapter5/lisamaitalk10.webp"
image lisamaitalk11 = "images/scenes/chapter5/lisamaitalk11.webp"

#Lisa
image lisamcmakeup1 = "images/scenes/chapter5/lisamcmakeup1.webp"
image lisamcmakeup2 = "images/scenes/chapter5/lisamcmakeup2.webp"
image lisainbed2 = "images/scenes/chapter5/lisainbed.webp"
#Mai
image maimcmakeup1 = "images/scenes/chapter5/maimcmakeup1.webp"
image maimcmakeup2 = "images/scenes/chapter5/maimcmakeup2.webp"
image maiinbed = "images/scenes/chapter5/maiinbed.webp"
#Kim
image kimseduce1 = "images/scenes/chapter5/kimseduce1.webp"
image kimseduce2 = "images/scenes/chapter5/kimseduce2.webp"
image kimseduce3 = "images/scenes/chapter5/kimseduce3.webp"
image kimseduce4 = "images/scenes/chapter5/kimseduce4.webp"
image kimseduce5 = "images/scenes/chapter5/kimseduce5.webp"
image kimseduce6 = "images/scenes/chapter5/kimseduce6.webp"
image kimseduce7 = "images/scenes/chapter5/kimseduce7.webp"
image kimseduce8 = "images/scenes/chapter5/kimseduce8.webp"
image kimseduce9 = "images/scenes/chapter5/kimseduce9.webp"
image kimseduce10 = "images/scenes/chapter5/kimseduce10.webp"

image kiminbed = "images/scenes/chapter5/kim in bed1.webp"
#Bella
image bellarobot1 = "images/scenes/chapter5/bellarobot1.webp"
image bellarobot2 = "images/scenes/chapter5/bellarobot2.webp"
image bellarobot3 = "images/scenes/chapter5/bellarobot3.webp"
image bellarobot4 = "images/scenes/chapter5/bellarobot4.webp"
image bellarobot5 = "images/scenes/chapter5/bellarobot5.webp"
image bellarobot6 = "images/scenes/chapter5/bellarobot6.webp"
image bellarobot7 = "images/scenes/chapter5/bellarobot7.webp"
image bellarobot8 = "images/scenes/chapter5/bellarobot8.webp"
#Crissy
image crissycaught1 = "images/scenes/chapter5/crissycaught1.webp"
image crissycaught2 = "images/scenes/chapter5/crissycaught2.webp"
image crissycaught3 = "images/scenes/chapter5/crissycaught3.webp"
image crissycaught4 = "images/scenes/chapter5/crissycaught4.webp"
image crissycaught5 = "images/scenes/chapter5/crissycaught5.webp"
image crissycaught6 = "images/scenes/chapter5/crissycaught6.webp"

#----------Chapter6---------------------#
#Bella
image bellavisit1 = "images/scenes/chapter6/bellavisit1.webp"
image bellavisit2 = "images/scenes/chapter6/bellavisit2.webp"
image bellavisit3 = "images/scenes/chapter6/bellavisit3.webp"
#Crissy
image crissypolice1 = "images/scenes/chapter6/crissypolice1.webp"
image crissypolice2 = "images/scenes/chapter6/crissypolice2.webp"
image crissybeg1 = "images/scenes/chapter6/crissybeg1.webp"
image mcfirstappearance ="images/scenes/chapter6/mcfirstappearance.webp"
#Kim
image kimvisit1 = "images/scenes/chapter6/kimvisit1.webp"
image kimvisit2 = "images/scenes/chapter6/kimvisit2.webp"
image kimvisit3 = "images/scenes/chapter6/kimvisit3.webp"
image kimvisit4 = "images/scenes/chapter6/kimvisit4.webp"
image kimvisit5 = "images/scenes/chapter6/kimvisit5.webp"
image kimvisit6 = "images/scenes/chapter6/kimvisit6.webp"
image kimvisit7 = "images/scenes/chapter6/kimvisit7.webp"
image kimvisit8 = "images/scenes/chapter6/kimvisit8.webp"
image kimvisit9 = "images/scenes/chapter6/kimvisit9.webp"
image kimvisit10 = "images/scenes/chapter6/kimvisit10.webp"
image kimvisit11 = "images/scenes/chapter6/kimvisit11.webp"
image kimvisit12 = "images/scenes/chapter6/kimvisit12.webp"
image kimvisit13 = "images/scenes/chapter6/kimvisit13.webp"
image kimvisit14 = "images/scenes/chapter6/kimvisit14.webp"
image kimvisit15 = "images/scenes/chapter6/kimvisit15.webp"
image kimvisit16 = "images/scenes/chapter6/kimvisit16.webp"

image kimmcmom1 = "images/scenes/chapter6/kimmcmom1.webp"
image kimmcmom2 = "images/scenes/chapter6/kimmcmom2.webp"
image kimmcmom3 = "images/scenes/chapter6/kimmcmom3.webp"
image kimmcmom4 = "images/scenes/chapter6/kimmcmom4.webp"
image kimmcmom5 = "images/scenes/chapter6/kimmcmom5.webp"
image kimmcmom6 = "images/scenes/chapter6/kimmcmom6.webp"
image kimmcmom7 = "images/scenes/chapter6/kimmcmom7.webp"
image kimmcmom8 = "images/scenes/chapter6/kimmcmom8.webp"
image kimmcmom9 = "images/scenes/chapter6/kimmcmom9.webp"
image kimmcmom10 = "images/scenes/chapter6/kimmcmom10.webp"
image kimmcmom11 = "images/scenes/chapter6/kimmcmom11.webp"
#Lisa
image lisavisit1 = "images/scenes/chapter6/lisavisit1.webp"
image lisavisit2 = "images/scenes/chapter6/lisavisit2.webp"
image lisavisit3 = "images/scenes/chapter6/lisavisit3.webp"
image lisavisit4 = "images/scenes/chapter6/lisavisit4.webp"
image lisavisit5 = "images/scenes/chapter6/lisavisit5.webp"
image lisavisit6 = "images/scenes/chapter6/lisavisit6.webp"
image lisavisit7 = "images/scenes/chapter6/lisavisit7.webp"
image lisavisit8 = "images/scenes/chapter6/lisavisit8.webp"
image lisavisit9 = "images/scenes/chapter6/lisavisit9.webp"
image lisavisit10 = "images/scenes/chapter6/lisavisit10.webp"
image lisavisit11 = "images/scenes/chapter6/lisavisit11.webp"
image lisavisit12 = "images/scenes/chapter6/lisavisit12.webp"
image lisavisit13 = "images/scenes/chapter6/lisavisit13.webp"
image lisavisit14 = "images/scenes/chapter6/lisavisit14.webp"
image lisavisit15 = "images/scenes/chapter6/lisavisit15.webp"

image lisamcmom1 = "images/scenes/chapter6/lisamcmom1.webp"
image lisamcmom2 = "images/scenes/chapter6/lisamcmom2.webp"
image lisamcmom3 = "images/scenes/chapter6/lisamcmom3.webp"
image lisamcmom4 = "images/scenes/chapter6/lisamcmom4.webp"
image lisamcmom5 = "images/scenes/chapter6/lisamcmom5.webp"
image lisamcmom6 = "images/scenes/chapter6/lisamcmom6.webp"
#Mai
image maivisit1 = "images/scenes/chapter6/maivisit1.webp"
image maivisit2 = "images/scenes/chapter6/maivisit2.webp"
image maivisit3 = "images/scenes/chapter6/maivisit3.webp"
image maivisit4 = "images/scenes/chapter6/maivisit4.webp"
image maivisit5 = "images/scenes/chapter6/maivisit5.webp"
image maivisit6 = "images/scenes/chapter6/maivisit6.webp"
image maivisit7 = "images/scenes/chapter6/maivisit7.webp"
image maivisit8 = "images/scenes/chapter6/maivisit8.webp"
image maivisit9 = "images/scenes/chapter6/maivisit9.webp"
image maivisit10 = "images/scenes/chapter6/maivisit10.webp"
image maivisit11 = "images/scenes/chapter6/maivisit11.webp"
image maivisit12 = "images/scenes/chapter6/maivisit12.webp"
image maivisit13 = "images/scenes/chapter6/maivisit13.webp"
image maivisit14 = "images/scenes/chapter6/maivisit14.webp"
image maivisit15 = "images/scenes/chapter6/maivisit15.webp"
image maivisit16 = "images/scenes/chapter6/maivisit16.webp"
#MC

image mconphone = "images/scenes/chapter6/mconphone.webp"
image mcsitsoncouch = "images/scenes/chapter6/mcsitsoncouch.webp"
image momintro = "images/scenes/chapter6/momintro1.webp"
image momintro2 = "images/scenes/chapter6/momintro2.webp"

#----Chapter7 -----------------#
#Guilty Verdict
image guiltyverdict = "images/scenes/chapter7/guiltyverdict.webp"
image maiguiltyverdict = "images/scenes/chapter7/maiguiltyverdict.webp"
image lisaguiltyverdict = "images/scenes/chapter7/lisaguiltyverdict.webp"
image kimnguiltyverdict = "images/scenes/chapter7/kimguiltyverdict.webp"
image mcinhandcuffs = "images/scenes/chapter7/mcinhandcuffs.webp"

#Not Guilty Verdict
image notguiltyverdict = "images/scenes/chapter7/notguiltyverdict.webp"
image mainotguiltyverdict = "images/scenes/chapter7/mainotguiltyverdict.webp"
image lisanotguiltyverdict = "images/scenes/chapter7/lisanotguiltyverdict.webp"
image kimnotguiltyverdict = "images/scenes/chapter7/kimnotguiltyverdict.webp"


#Mom/Court
image judgeenters = "images/scenes/chapter7/judgeenters.webp"
image kimincriminate = "images/scenes/chapter7/kimincriminate.webp"
image lisaincriminate = "images/scenes/chapter7/lisaincriminate.webp"
image maiincriminate = "images/scenes/chapter7/maiincriminate.webp"
image maiswearsoath = "images/scenes/chapter7/maiswearsoath.webp"
image lisaswearsoath = "images/scenes/chapter7/lisaswearsoath.webp"
image kimswearsoath = "images/scenes/chapter7/kimswearsoath.webp"
image bellaswearsoath = "images/scenes/chapter7/bellaswearsoath.webp"
image crissyswearsoath = "images/scenes/chapter7/crissyswearsoath.webp"
image momtalk1 = "images/scenes/chapter7/momtalk1.webp"
image momtalk2 = "images/scenes/chapter7/momtalk2.webp"
image momtalk3 = "images/scenes/chapter7/momtalk3.webp"
image momtalk4 = "images/scenes/chapter7/momtalk4.webp"
image momtalk5 = "images/scenes/chapter7/momtalk5.webp"
image momtalk6 = "images/scenes/chapter7/momtalk6.webp"
image momtalk7 = "images/scenes/chapter7/momtalk7.webp"

#-------------------Epilogue----------------#
#Bad Ending
image badending1 = "images/scenes/epilogue/badending1.webp"
image badending2 = "images/scenes/epilogue/badending2.webp"
image badending3 = "images/scenes/epilogue/badending3.webp"
image badending4 = "images/scenes/epilogue/badending4.webp"
image badending5 = "images/scenes/epilogue/badending5.webp"
image badending6 = "images/scenes/epilogue/badending6.webp"
image badending7 = "images/scenes/epilogue/badending7.webp"
image badending8 = "images/scenes/epilogue/badending8.webp"
image badending9 = "images/scenes/epilogue/badending9.webp"
image badending10 = "images/scenes/epilogue/badending10.webp"
image badending11 = "images/scenes/epilogue/badending11.webp"

#Neutral Endings
image neutralending1 = "images/scenes/epilogue/neutralending1.webp"
image neutralending2 = "images/scenes/epilogue/neutralending2.webp"
image neutralending3 = "images/scenes/epilogue/neutralending3.webp"


image kimneutralending1 = "images/scenes/epilogue/kimneutralending1.webp"
image kimneutralending2 = "images/scenes/epilogue/kimneutralending2.webp"
image kimneutralending3 = "images/scenes/epilogue/kimneutralending3.webp"

image kimneutralending5 = "images/scenes/epilogue/kimneutralending5.webp"
image kimneutralending6 = "images/scenes/epilogue/kimneutralending6.webp"
image kimneutralending7 = "images/scenes/epilogue/kimneutralending7.webp"
image kimneutralending8 = "images/scenes/epilogue/kimneutralending8.webp"

image kimneutralending11 = "images/scenes/epilogue/kimneutralending11.webp"

image lisaneutralending1 = "images/scenes/epilogue/lisaneutralending1.webp"
image lisaneutralending2 = "images/scenes/epilogue/lisaneutralending2.webp"
image lisaneutralending3 = "images/scenes/epilogue/lisaneutralending3.webp"
image lisaneutralending4 = "images/scenes/epilogue/lisaneutralending4.webp"
image lisaneutralending5 = "images/scenes/epilogue/lisaneutralending5.webp"
image lisaneutralending6 = "images/scenes/epilogue/lisaneutralending6.webp"
image lisaneutralending7 = "images/scenes/epilogue/lisaneutralending7.webp"

image maineutralending1 = "images/scenes/epilogue/maineutralending1.webp"
image maineutralending2 = "images/scenes/epilogue/maineutralending2.webp"
image maineutralending3 = "images/scenes/epilogue/maineutralending3.webp"
image maineutralending4 = "images/scenes/epilogue/maineutralending4.webp"
image maineutralending5 = "images/scenes/epilogue/maineutralending5.webp"
image maineutralending6 = "images/scenes/epilogue/maineutralending6.webp"

image dadreturnsneutralending = "images/scenes/epilogue/dadreturnsneutralending.webp"

image neutralendingcard = "images/scenes/epilogue/neutralendingcard.webp"
#Good Endings
image kimgoodending1 = "images/scenes/epilogue/kimgoodending1.webp"
image kimgoodending2 = "images/scenes/epilogue/kimgoodending2.webp"
image kimgoodending3 = "images/scenes/epilogue/kimgoodending3.webp"
image kimgoodending4 = "images/scenes/epilogue/kimgoodending4.webp"
image kimgoodending5 = "images/scenes/epilogue/kimgoodending5.webp"
image kimgoodending6 = "images/scenes/epilogue/kimgoodending6.webp"
image kimgoodendingcard = "images/scenes/epilogue/kimgoodendingcard.webp"

image lisagoodending1 = "images/scenes/epilogue/lisagoodending1.webp"
image lisagoodending2 = "images/scenes/epilogue/lisagoodending2.webp"
image lisagoodending3 = "images/scenes/epilogue/lisagoodending3.webp"
image lisagoodendingcard = "images/scenes/epilogue/kimgoodendingcard.webp"

image maigoodending1 = "images/scenes/epilogue/maigoodending1.webp"
image maigoodending2 = "images/scenes/epilogue/maigoodending2.webp"
image maigoodending3 = "images/scenes/epilogue/maigoodending3.webp"
image maigoodending4 = "images/scenes/epilogue/maigoodending4.webp"
image maigoodending5 = "images/scenes/epilogue/maigoodending5.webp"
image maigoodendingcard = "images/scenes/epilogue/kimgoodendingcard.webp"

image bellagoodending1 = "images/scenes/epilogue/bellagoodending1.webp"
image bellagoodending2 = "images/scenes/epilogue/bellagoodending2.webp"
image bellagoodending3 = "images/scenes/epilogue/bellagoodending3.webp"

image crissygoodending1 = "images/scenes/epilogue/crissygoodending.webp"
image crissygoodending2 = "images/scenes/epilogue/crissygoodending2.webp"
image crissygoodendingcard = "images/scenes/epilogue/crissygoodendingcard.webp"

#solo endings
image sologoodending = "images/scenes/epilogue/sologoodending.webp"
image sologoodendingcard = "images/scenes/epilogue/sologoodendingcard.webp"
image soloneutralending = "images/scenes/epilogue/soloneutralending.webp"
image soloneutralendingcard = "images/scenes/epilogue/soloneutralendingcard.webp"

#newsreporter ending
image newsreporterending1 = "images/scenes/epilogue/newsreporterending1.webp"
image newsreporterending2 = "images/scenes/epilogue/newsreporterending2.webp"
image newsreporterending3 = "images/scenes/epilogue/newsreporterending3.webp"
image newsreporterending4 = "images/scenes/epilogue/newsreporterending4.webp"
