#Bella
image bella curious1 = "images/Bella/bella_curious1.png"
image bella curious2 = "images/Bella/bella_curious2.png"
image bella curious3 = "images/Bella/bella_curious3.png"
image bella curious4 = "images/Bella/bella_curious4.png"

image bella sad1 = "images/Bella/bella_sad1.png"
image bella sad2 = "images/Bella/bella_sad2.png"
image bella sad3 = "images/Bella/bella_sad3.png"
image bella sad4 = "images/Bella/bella_sad4.png"
image bella sad5 = "images/Bella/bella_sad5.png"
image bella sad6 = "images/Bella/bella_sad6.png"
image bella sad7 = "images/Bella/bella_sad7.png"

image bella serious1 = "images/Bella/bella_serious1.png"
image bella serious2 = "images/Bella/bella_serious2.png"
image bella serious3 = "images/Bella/bella_serious3.png"
image bella serious4 = "images/Bella/bella_serious4.png"
image bella serious5 = "images/Bella/bella_serious5.png"
image bella serious6 = "images/Bella/bella_serious6.png"
image bella serious7 = "images/Bella/bella_serious7.png"
image bella serious8 = "images/Bella/bella_serious8.png"

image bella smile1 = "images/Bella/bella_smile1.png"
image bella smile2 = "images/Bella/bella_smile2.png"
image bella smile3 = "images/Bella/bella_smile3.png"
image bella smile4 = "images/Bella/bella_smile4.png"

image bella surprised1 = "images/Bella/bella_surprised1.png"
image bella surprised2 = "images/Bella/bella_surprised2.png"
image bella surprised3 = "images/Bella/bella_surprised3.png"
image bella surprised4 = "images/Bella/bella_surprised4.png"

image bella court1 = "images/Bella/bella_court1.png"
image bella court2 = "images/Bella/bella_court2.png"
image bella court3 = "images/Bella/bella_court3.png"
image bella court4 = "images/Bella/bella_court4.png"
image bella court5 = "images/Bella/bella_court5.png"
#Crissy
image crissy angry1 = "images/Crissy/crissy_angry1.png"
image crissy angry2 = "images/Crissy/crissy_angry2.png"
image crissy angry3 = "images/Crissy/crissy_angry3.png"
image crissy angry4 = "images/Crissy/crissy_angry4.png"
image crissy angry5 = "images/Crissy/crissy_angry5.png"
image crissy angry6 = "images/Crissy/crissy_angry6.png"
image crissy angry7 = "images/Crissy/crissy_angry7.png"
image crissy angry8 = "images/Crissy/crissy_angry8.png"
image crissy angry9 = "images/Crissy/crissy_angry9.png"
image crissy angry10 = "images/Crissy/crissy_angry10.png"
image crissy angry11 = "images/Crissy/crissy_angry11.png"
image crissy angry12 = "images/Crissy/crissy_angry12.png"
image crissy angry13 = "images/Crissy/crissy_angry13.png"
image crissy angry14 = "images/Crissy/crissy_angry14.png"

image crissy flirt1 = "images/Crissy/crissy_flirt1.png"
image crissy flirt2 = "images/Crissy/crissy_flirt2.png"
image crissy flirt3 = "images/Crissy/crissy_flirt3.png"
image crissy flirt4 = "images/Crissy/crissy_flirt4.png"

image crissy sad1 = "images/Crissy/crissy_sad1.png"
image crissy sad2 = "images/Crissy/crissy_sad2.png"
image crissy sad3 = "images/Crissy/crissy_sad3.png"
image crissy sad4 = "images/Crissy/crissy_sad4.png"
image crissy sad5 = "images/Crissy/crissy_sad5.png"
image crissy sad6 = "images/Crissy/crissy_sad6.png"
image crissy sad7 = "images/Crissy/crissy_sad7.png"
image crissy sad8 = "images/Crissy/crissy_sad8.png"
image crissy sad9 = "images/Crissy/crissy_sad9.png"
image crissy sad10 = "images/Crissy/crissy_sad10.png"
image crissy sad11 = "images/Crissy/crissy_sad11.png"
image crissy sad12 = "images/Crissy/crissy_sad12.png"

image crissy serious1 = "images/Crissy/crissy_serious1.png"
image crissy serious2 = "images/Crissy/crissy_serious2.png"
image crissy serious3 = "images/Crissy/crissy_serious3.png"
image crissy serious4 = "images/Crissy/crissy_serious4.png"
image crissy serious5 = "images/Crissy/crissy_serious5.png"
image crissy serious6 = "images/Crissy/crissy_serious6.png"
image crissy serious7 = "images/Crissy/crissy_serious7.png"
image crissy serious8 = "images/Crissy/crissy_serious8.png"
image crissy serious9 = "images/Crissy/crissy_serious9.png"
image crissy serious10 = "images/Crissy/crissy_serious10.png"
image crissy serious11 = "images/Crissy/crissy_serious11.png"
image crissy serious12 = "images/Crissy/crissy_serious12.png"

image crissy smile1 = "images/Crissy/crissy_sad1.png"
image crissy smile2 = "images/Crissy/crissy_sad2.png"
image crissy smile3 = "images/Crissy/crissy_sad3.png"
image crissy smile4 = "images/Crissy/crissy_sad4.png"
image crissy smile5 = "images/Crissy/crissy_sad5.png"
image crissy smile6 = "images/Crissy/crissy_sad6.png"
image crissy smile7 = "images/Crissy/crissy_sad7.png"
image crissy smile8 = "images/Crissy/crissy_sad8.png"
image crissy smile9 = "images/Crissy/crissy_sad9.png"
image crissy smile10 = "images/Crissy/crissy_sad10.png"
image crissy smile11 = "images/Crissy/crissy_sad11.png"

image crissy surprised1 = "images/Crissy/crissy_surprised1.png"
image crissy surprised2 = "images/Crissy/crissy_surprised2.png"
image crissy surprised3 = "images/Crissy/crissy_surprised3.png"

image crissy court1 = "images/Crissy/crissy_court1.png"
image crissy court2 = "images/Crissy/crissy_court2.png"
image crissy court3 = "images/Crissy/crissy_court3.png"
image crissy court4 = "images/Crissy/crissy_court4.png"
#Kim
image kim angry1 = "images/Kim/Kim_angry1.png"
image kim angry2 = "images/Kim/Kim_angry2.png"
image kim angry3 = "images/Kim/Kim_angry3.png"
image kim angry4 = "images/Kim/Kim_angry4.png"
image kim angry5 = "images/Kim/Kim_angry5.png"
image kim angry6 = "images/Kim/Kim_angry6.png"
image kim angry7 = "images/Kim/Kim_angry7.png"
image kim angry8 = "images/Kim/Kim_angry8.png"
image kim angry9 = "images/Kim/Kim_angry9.png"
image kim angry10 = "images/Kim/Kim_angry10.png"
image kim angry11 = "images/Kim/Kim_angry11.png"

image kim sad1 = "images/Kim/Kim_sad1.png"
image kim sad2 = "images/Kim/Kim_sad2.png"
image kim sad3 = "images/Kim/Kim_sad3.png"
image kim sad4 = "images/Kim/Kim_sad4.png"
image kim sad5 = "images/Kim/Kim_sad5.png"
image kim sad6 = "images/Kim/Kim_sad6.png"
image kim sad7 = "images/Kim/Kim_sad7.png"
image kim sad8 = "images/Kim/Kim_sad8.png"
image kim sad9 = "images/Kim/Kim_sad9.png"
image kim sad10 = "images/Kim/Kim_sad10.png"

image kim serious1 = "images/Kim/Kim_serious1.png"
image kim serious2 = "images/Kim/Kim_serious2.png"
image kim serious3 = "images/Kim/Kim_serious3.png"
image kim serious4 = "images/Kim/Kim_serious4.png"
image kim serious5 = "images/Kim/Kim_serious5.png"
image kim serious6 = "images/Kim/Kim_serious6.png"
image kim serious7 = "images/Kim/Kim_serious7.png"
image kim serious8 = "images/Kim/Kim_serious8.png"
image kim serious9 = "images/Kim/Kim_serious9.png"
image kim serious10 = "images/Kim/Kim_serious10.png"


image kim smile1 = "images/Kim/Kim_smile1.png"
image kim smile2 = "images/Kim/Kim_smile2.png"
image kim smile3 = "images/Kim/Kim_smile3.png"
image kim smile4 = "images/Kim/Kim_smile4.png"
image kim smile5 = "images/Kim/Kim_smile5.png"
image kim smile6 = "images/Kim/Kim_smile6.png"
image kim smile7 = "images/Kim/Kim_smile7.png"
image kim smile8 = "images/Kim/Kim_smile8.png"
image kim smile9 = "images/Kim/Kim_smile9.png"
image kim smile10 = "images/Kim/Kim_smile10.png"

image kim surprised = "images/Kim/Kim_Surprised1.png."

image kim frumpy1 = "images/Kim/Kim_frumpy1.png"
image kim frumpy2 = "images/Kim/Kim_frumpy2.png"
image kim frumpy3 = "images/Kim/Kim_frumpy3.png"
image kim frumpy4 = "images/Kim/Kim_frumpy4.png"
image kim frumpy5 = "images/Kim/Kim_frumpy5.png"
image kim frumpy6 = "images/Kim/Kim_frumpy6.png"
image kim frumpy7 = "images/Kim/Kim_frumpy7.png"
image kim frumpy8 = "images/Kim/Kim_frumpy8.png"
image kim frumpy9 = "images/Kim/Kim_frumpy9.png"
image kim frumpy10 = "images/Kim/Kim_frumpy10.png"
image kim frumpy11 = "images/Kim/Kim_frumpy11.png"
image kim frumpy12 = "images/Kim/Kim_frumpy12.png"
image kim frumpy13 = "images/Kim/Kim_frumpy13.png"
image kim frumpy14 = "images/Kim/Kim_frumpy14.png"
image kim frumpy15 = "images/Kim/Kim_frumpy15.png"
image kim frumpy16 = "images/Kim/Kim_frumpy16.png"
image kim frumpy17 = "images/Kim/Kim_frumpy17.png"

image kim court1 = "images/Kim/Kim_court1.png"
image kim court2 = "images/Kim/Kim_court2.png"
image kim court3 = "images/Kim/Kim_court3.png"
image kim court4 = "images/Kim/Kim_court4.png"
image kim court5 = "images/Kim/Kim_court5.png"
image kim court6 = "images/Kim/Kim_court6.png"

#Lisa
image lisa court1 = "images/Lisa/Lisa_court1.png"
image lisa court2 = "images/Lisa/Lisa_court2.png"
image lisa court3 = "images/Lisa/Lisa_court3.png"
image lisa court4 = "images/Lisa/Lisa_court4.png"
image lisa court5 = "images/Lisa/Lisa_court5.png"
image lisa court6 = "images/Lisa/Lisa_court6.png"

image lisa angry1 = "images/Lisa/Lisa_angry1.png"
image lisa angry2 = "images/Lisa/Lisa_angry2.png"
image lisa angry3 = "images/Lisa/Lisa_angry3.png"
image lisa angry4 = "images/Lisa/Lisa_angry4.png"
image lisa angry5 = "images/Lisa/Lisa_angry5.png"

image lisa flirt1 = "images/Lisa/Lisa_flirt1.png"
image lisa flirt2 = "images/Lisa/Lisa_flirt2.png"
image lisa flirt3 = "images/Lisa/Lisa_flirt3.png"
image lisa flirt4 = "images/Lisa/Lisa_flirt4.png"

image lisa sad1 = "images/Lisa/Lisa_sad1.png"
image lisa sad2 = "images/Lisa/Lisa_sad2.png"
image lisa sad3 = "images/Lisa/Lisa_sad3.png"
image lisa sad4 = "images/Lisa/Lisa_sad4.png"
image lisa sad5 = "images/Lisa/Lisa_sad5.png"
image lisa sad6 = "images/Lisa/Lisa_sad6.png"
image lisa sad7 = "images/Lisa/Lisa_sad7.png"
image lisa sad8 = "images/Lisa/Lisa_sad8.png"
image lisa sad9 = "images/Lisa/Lisa_sad9.png"

image lisa serious1 = "images/Lisa/Lisa_serious1.png"
image lisa serious2 = "images/Lisa/Lisa_serious2.png"
image lisa serious3 = "images/Lisa/Lisa_serious3.png"
image lisa serious4 = "images/Lisa/Lisa_serious4.png"
image lisa serious5 = "images/Lisa/Lisa_serious5.png"
image lisa serious6 = "images/Lisa/Lisa_serious6.png"
image lisa serious7 = "images/Lisa/Lisa_serious7.png"
image lisa serious8 = "images/Lisa/Lisa_serious8.png"
image lisa serious9 = "images/Lisa/Lisa_serious9.png"
image lisa serious10 = "images/Lisa/Lisa_serious10.png"
image lisa serious11 = "images/Lisa/Lisa_serious11.png"
image lisa serious12 = "images/Lisa/Lisa_serious12.png"
image lisa serious13 = "images/Lisa/Lisa_serious13.png"
image lisa serious14 = "images/Lisa/Lisa_serious14.png"

image lisa smile1 = "images/Lisa/Lisa_smile1.png"
image lisa smile2 = "images/Lisa/Lisa_smile2.png"
image lisa smile3 = "images/Lisa/Lisa_smile3.png"
image lisa smile4 = "images/Lisa/Lisa_smile4.png"
image lisa smile5 = "images/Lisa/Lisa_smile5.png"
image lisa smile6 = "images/Lisa/Lisa_smile6.png"

image lisa surprise1 = "images/Lisa/Lisa_surpise1.png"
image lisa surprise2 = "images/Lisa/Lisa_surpise2.png"
image lisa surprise3 = "images/Lisa/Lisa_surpise3.png"
image lisa surprise4 = "images/Lisa/Lisa_surpise4.png"
image lisa surprise5 = "images/Lisa/Lisa_surpise5.png"
image lisa surprise6 = "images/Lisa/Lisa_surpise6.png"
image lisa surprise7 = "images/Lisa/Lisa_surpise7.png"

#Mai
image mai cynic1 = "images/Mai/Mai_cynic1.png"
image mai cynic2 = "images/Mai/Mai_cynic2.png"

image mai curious1 = "images/Mai/Mai_curious1.png"
image mai curious2 = "images/Mai/Mai_curious2.png"

image mai sad1 = "images/Mai/Mai_sad1.png"
image mai sad2 = "images/Mai/Mai_sad2.png"
image mai sad3 = "images/Mai/Mai_sad3.png"
image mai sad4 = "images/Mai/Mai_sad4.png"
image mai sad5 = "images/Mai/Mai_sad5.png"
image mai sad6 = "images/Mai/Mai_sad6.png"
image mai sad7 = "images/Mai/Mai_sad7.png"
image mai sad8 = "images/Mai/Mai_sad8.png"
image mai sad9 = "images/Mai/Mai_sad9.png"
image mai sad10 = "images/Mai/Mai_sad10.png"
image mai sad11 = "images/Mai/Mai_sad11.png"

image mai serious1 = "images/Mai/Mai_serious1.png"
image mai serious2 = "images/Mai/Mai_serious2.png"
image mai serious3 = "images/Mai/Mai_serious3.png"
image mai serious4 = "images/Mai/Mai_serious4.png"

image mai smile1 = "images/Mai/Mai_smile1.png"
image mai smile2 = "images/Mai/Mai_smile2.png"
image mai smile3 = "images/Mai/Mai_smile3.png"
image mai smile4 = "images/Mai/Mai_smile4.png"
image mai smile5 = "images/Mai/Mai_smile5.png"
image mai smile6 = "images/Mai/Mai_smile6.png"
image mai smile7 = "images/Mai/Mai_smile7.png"
image mai smile8 = "images/Mai/Mai_smile8.png"

image mai flirt1 = "images/Mai/mai_flirt1.png"
image mai flirt2 = "images/Mai/mai_flirt2.png"
image mai flirt3 = "images/Mai/mai_flirt3.png"
image mai flirt4 = "images/Mai/mai_flirt4.png"
image mai flirt5 = "images/Mai/mai_flirt5.png"
image mai flirt6 = "images/Mai/mai_flirt6.png"

image mai surprise = "images/Mai/mai_surpise1.png"

image mai court1 = "images/Mai/Mai_Court1.png"
image mai court2 = "images/Mai/Mai_Court2.png"
image mai court3 = "images/Mai/Mai_Court3.png"
image mai court4 = "images/Mai/Mai_Court4.png"
image mai court5 = "images/Mai/Mai_Court5.png"

#John
image john = "images/John/1.png"
image john happy1 = "images/John/johnhappy_1.png"
image john happy2 = "images/John/johnhappy_2.png"
image john happy3 = "images/John/johnhappy_3.png"
image john happy4 = "images/John/johnhappy_4.png"
image john happy5 = "images/John/johnhappy_5.png"
image john happy6 = "images/John/johnhappy_6.png"
image john happy7 = "images/John/johnhappy_7.png"


image john stern1 = "images/John/johnstern_1.png"
image john stern2 = "images/John/johnstern_2.png"
image john stern3 = "images/John/johnstern_3.png"
image john stern4 = "images/John/johnstern_4.png"
image john stern5 = "images/John/johnstern_5.png"
image john stern6 = "images/John/johnstern_6.png"
image john stern7 = "images/John/johnstern_7.png"
image john stern8 = "images/John/johnstern_8.png"
image john stern9 = "images/John/johnstern_9.png"

image john right1 = "images/John/johnright_1.png"
image john right2 = "images/John/johnright_2.png"

image john laugh1 = "images/John/johnlaugh_1.png"
image john laugh2 = "images/John/johnlaugh_animation08.png"
    
#Judge
image judge1 = "images/Judge/Judge1.png"
image judge2 = "images/Judge/Judge2.png"
image judge3 = "images/Judge/Judge3.png"
image judge4 = "images/Judge/Judge4.png"
image judge5 = "images/Judge/Judge5.png"
image judge6 = "images/Judge/Judge6.png"
#Iris
image iris1 = "images/Iris/Iris1.png"

image iris3 = "images/Iris/Iris3.png"
image iris4 = "images/Iris/Iris4.png"
image iris5 = "images/Iris/Iris5.png"
image iris6 = "images/Iris/Iris6.png"
image iris7 = "images/Iris/Iris7.png"
image iris8 = "images/Iris/Iris8.png"
image iris9 = "images/Iris/Iris9.png"
image iris10 = "images/Iris/Iris10.png"
image iris11 = "images/Iris/Iris11.png"

image lara angry1 = "images/Lara/Lara_angry1.png"
image lara angry2 = "images/Lara/Lara_angry2.png"
image lara angry3 = "images/Lara/Lara_angry3.png"
image lara angry4 = "images/Lara/Lara_angry4.png"
image lara angry5 = "images/Lara/Lara_angry5.png"
image lara angry6 = "images/Lara/Lara_angry6.png"
image lara angry7 = "images/Lara/Lara_angry7.png"

image lara sad1 = "images/Lara/Lara_sad1.png"
image lara sad2 = "images/Lara/Lara_sad2.png"

image lara serious1 = "images/Lara/Lara_serious1.png"
image lara serious2 = "images/Lara/Lara_serious2.png"
image lara serious3 = "images/Lara/Lara_serious3.png"
image lara serious4 = "images/Lara/Lara_serious4.png"
image lara serious5 = "images/Lara/Lara_serious5.png"
image lara serious6 = "images/Lara/Lara_serious6.png"
image lara serious7 = "images/Lara/Lara_serious7.png"
image lara serious8 = "images/Lara/Lara_serious8.png"
image lara serious9 = "images/Lara/Lara_serious9.png"
image lara serious10 = "images/Lara/Lara_serious10.png"
image lara serious11 = "images/Lara/Lara_serious11.png"
image lara serious12 = "images/Lara/Lara_serious12.png"

image lara smile1 = "images/Lara/Lara_smile1.png"
image lara smile2 = "images/Lara/Lara_smile2.png"
image lara smile3 = "images/Lara/Lara_smile3.png"
image lara smile4 = "images/Lara/Lara_smile4.png"
image lara smile5 = "images/Lara/Lara_smile5.png"
image lara smile6 = "images/Lara/Lara_smile6.png"
image lara smile7 = "images/Lara/Lara_smile7.png"
image lara smile8 = "images/Lara/Lara_smile8.png"
